// path: ~/02_Dev/aliceinhelloworld/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Pretendard Variable Font
const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  weight: "100 900", // 전체 범위
});

// Hack 폰트
const hack = localFont({
  src: [
    {
      path: "../public/fonts/hack-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/hack-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/hack-italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/hack-bolditalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-hack",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${hack.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased">{children}</body>
    </html>
  );
}
