
import fs from 'fs';
import path from 'path';

const contentDir = path.join(process.cwd(), 'content/blog');
const outputFile = path.join(process.cwd(), 'lib/post-map.ts');

function getFilesRecursively(dir: string): string[] {
  let results: string[] = [];
  const list = fs.readdirSync(dir);
  list.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat && stat.isDirectory()) {
      results = results.concat(getFilesRecursively(filePath));
    } else {
      if (file.endsWith('.mdx')) {
        results.push(filePath);
      }
    }
  });
  return results;
}

if (!fs.existsSync(contentDir)) {
  console.error("Content directory not found!");
  process.exit(1);
}

const files = getFilesRecursively(contentDir);
const imports: string[] = [];

files.forEach(file => {
  // relative path from content/blog
  const relPath = path.relative(contentDir, file);
  // remove extension
  const id = relPath.replace(/\.mdx$/, '');

  // path for import (using alias @)
  const importPath = `@/content/blog/${relPath}`;

  imports.push(`  '${id}': dynamic(() => import('${importPath}'), { loading: () => null, ssr: false }),`);
});

const fileContent = `// Auto-generated by scripts/generate-post-map.ts
import dynamic from 'next/dynamic';
import React from 'react';

export const POST_MAP: Record<string, React.ComponentType> = {
${imports.join('\n')}
};
`;

fs.writeFileSync(outputFile, fileContent);
console.log(`Generated post map with ${imports.length} entries.`);
